name: lambda-deployment

on:
  push:
    branches:
      - development

jobs:
  deploy_source:
    name: Build And Deploy Lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install dependencies, Build application and Zip dist folder contents
        run: npm install && zip -qq -r bundle.zip .
      - name: Deploying Zip To Lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: lambda-starter-development
          zip_file: bundle.zip
